/**
 * This class is generated by jOOQ
 */
package nz.denys.restservice;


import javax.annotation.Generated;

import nz.denys.restservice.tables.Flight;


/**
 * Convenience access to all tables in flight
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table flight.flight
	 */
	public static final Flight FLIGHT = nz.denys.restservice.tables.Flight.FLIGHT;
}
